apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "m2repo"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "namaste-pipeline"
spec:
  source:
    git:
      uri: "https://github.com/gourp/namaste"
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: "Jenkinsfile"
